import assert from "node:assert/strict";
import { undo, redo, isolateHistory } from "@codemirror/commands";
import type { EditorState, Transaction } from "@codemirror/state";
import { agentMessagePlainText, withAgentResourceId } from "@shared/agent-message";
import { agentComposerClipboardText, agentComposerStateToMessage, composerResources, createAgentComposerState, insertAgentComposerResource, insertAgentComposerResourceTransaction, isAgentComposerEmpty } from "./agent-composer";
import { composeAgentMessage } from "./agent-message";
const resource = withAgentResourceId({ kind: "runsql", label: "Orders query", sql: "select * from orders", sourcePath: "orders.md", locator: { blockId: "one", blockIndex: 0 } });
const original = composeAgentMessage("Compare ", resource, " with yesterday\nthen explain");
let state = createAgentComposerState(original);
assert.deepEqual(agentComposerStateToMessage(state), original);
assert.equal(isAgentComposerEmpty(state), false);
state = insertAgentComposerResource(state, resource, { collapseSelectionToHead: true });
assert.equal(agentComposerStateToMessage(state).resources.length, 1);
assert.equal(agentComposerStateToMessage(state).segments.filter(s => s.kind === "resource").length, 2);
assert.match(agentComposerClipboardText(state), /@RunSQL · Orders query/);
assert.doesNotMatch(agentComposerClipboardText(state), /select \*/);
let mixed = createAgentComposerState({ version: 1, segments: [{ kind: "text", text: "中文ABC混合123" }], resources: [] });
mixed = mixed.update({ selection: { anchor: "中文ABC".length } }).state;
mixed = insertAgentComposerResource(mixed, resource, { collapseSelectionToHead: true });
mixed = mixed.update({ changes: { from: mixed.selection.main.head, insert: "AFTER" } }).state;
assert.equal(agentMessagePlainText(agentComposerStateToMessage(mixed)), "中文ABC [runsql: Orders query] AFTER混合123");
let history = createAgentComposerState({ version: 1, segments: [{ kind: "text", text: "before" }], resources: [] });
history = insertAgentComposerResource(history, resource);
function command(cmd: typeof undo) { return cmd({ state: history, dispatch: (tr: Transaction) => { history = tr.state; } }); }
assert.ok(command(undo)); assert.equal(history.doc.toString(), "before");
assert.ok(command(redo)); assert.equal(history.field(composerResources).length, 1);
const position = history.field(composerResources)[0].from;
history = history.update({ changes: { from: position, to: position + 1 }, userEvent: "delete.backward", annotations: isolateHistory.of("full") }).state;
assert.equal(history.field(composerResources).length, 0);
assert.ok(command(undo)); assert.equal(history.field(composerResources).length, 1);
assert.deepEqual(agentComposerStateToMessage(history).resources[0], resource);
const savedState: EditorState = history;
assert.deepEqual(agentComposerStateToMessage(savedState), agentComposerStateToMessage(history));
let trigger = createAgentComposerState({ version: 1, segments: [{ kind: "text", text: "@orders" }], resources: [] });
trigger = trigger.update(insertAgentComposerResourceTransaction(trigger, resource, { from: 0, to: 7, trailingSpaceAtEnd: true })).state;
assert.equal(agentMessagePlainText(agentComposerStateToMessage(trigger)), "[runsql: Orders query] ");
const pasted = createAgentComposerState({ version: 1, segments: [{ kind: "text", text: agentComposerClipboardText(trigger) }], resources: [] });
assert.equal(agentComposerStateToMessage(pasted).resources.length, 0);
const missing = createAgentComposerState({ version: 1, segments: [{ kind: "resource", resourceId: "missing" }], resources: [] });
assert.equal(agentMessagePlainText(agentComposerStateToMessage(missing)), "[missing resource]");
console.log("Composer: ordered references, Unicode insertion, visible clipboard, reference deletion and undo/redo passed.");
