import assert from "node:assert/strict";
import { MySQL, PostgreSQL } from "@codemirror/lang-sql";
import { composerSqlRegions, formatComposerSql } from "./composer-sql";
const mixed = "查一下这些城市\nSELECT city, revenue\nFROM sales\n\n然后解释差异";
const regions = composerSqlRegions(mixed);
assert.equal(regions.length, 1);
assert.equal(mixed.slice(regions[0].from, regions[0].to), "SELECT city, revenue\nFROM sales");
const formatted = formatComposerSql(mixed, mixed.indexOf("revenue"), mixed.indexOf("revenue"), MySQL)!;
assert.ok(formatted.text.includes("SELECT"));
assert.equal(mixed.slice(0, formatted.from), "查一下这些城市\n");
assert.equal(mixed.slice(formatted.to), "\n\n然后解释差异");
assert.equal(formatComposerSql(mixed, 2, 2, MySQL), null);
assert.equal(composerSqlRegions("Which table should I use?").length, 0);
assert.equal(composerSqlRegions("select 'x;y' as value; explain this")[0].to, "select 'x;y' as value;".length);
assert.equal(composerSqlRegions("select 'a\n\nb' as value").length, 1);
assert.deepEqual(composerSqlRegions("```python\nselect text\n```"), []);
const fenced = "Before\n```sql\nselect * from orders\n```\nAfter";
assert.equal(fenced.slice(composerSqlRegions(fenced)[0].from, composerSqlRegions(fenced)[0].to), "select * from orders");
assert.equal(formatComposerSql("select \uFFFC", 0, 8, MySQL), null);
assert.ok(formatComposerSql("select x::text from y", 0, 21, PostgreSQL));
console.log("Composer SQL regions: mixed prose, quoted delimiters, fences, format ranges and dialects passed.");
