import assert from "node:assert/strict";
import { Compartment, EditorState, StateEffect, type Transaction } from "@codemirror/state";
import { autocompletion } from "@codemirror/autocomplete";
import { undo } from "@codemirror/commands";
import { MySQL } from "@codemirror/lang-sql";
import { syntaxTree } from "@codemirror/language";
import { configureAgentComposerState, createAgentComposerState, insertAgentComposerResource, agentComposerStateToMessage } from "./agent-composer";
import { createComposerSqlField } from "./composer-sql-state";

const base = createAgentComposerState({version:1,segments:[{kind:"text",text:"SELECT 1"}],resources:[]});
const oldUi = new Compartment(), newUi = new Compartment();
const oldCompletion = autocompletion({override:[()=>null]});
const newCompletion = autocompletion({override:[()=>null]});
const legacy = base.update({effects:StateEffect.appendConfig.of(oldUi.of(oldCompletion))}).state;
assert.throws(()=>legacy.update({effects:StateEffect.appendConfig.of(newUi.of(newCompletion))}).state,/Config merge conflict for field override/);
let restored = configureAgentComposerState(legacy,newUi.of(newCompletion));
assert.equal(restored.doc.toString(),"SELECT 1");
restored = insertAgentComposerResource(restored,{kind:"runsql",label:"Source",sql:"SELECT 42"});
const message = agentComposerStateToMessage(restored);
const model = configureAgentComposerState(restored);
assert.equal(oldUi.get(model),undefined);
assert.equal(newUi.get(model),undefined);
for (let i=0;i<5;i++) restored = configureAgentComposerState(restored,new Compartment().of(autocompletion({override:[()=>null]})));
assert.deepEqual(agentComposerStateToMessage(restored),message);
assert.ok(undo({state:restored,dispatch:(tr:Transaction)=>{restored=tr.state;}}));
assert.equal(restored.doc.toString(),"SELECT 1");
assert.equal(agentComposerStateToMessage(restored).resources.length,0);

const field = createComposerSqlField(MySQL);
let state = EditorState.create({doc:"分析说明\n```sql\nSELECT city FROM sales\n```",extensions:field});
const sqlState = state.field(field)[0]!.state;
state = state.update({changes:{from:0,insert:"Please "}}).state;
assert.equal(state.field(field)[0]!.state,sqlState,"prose edits must reuse the SQL parse state");
const beforeSelection = state.field(field);
state = state.update({selection:{anchor:2}}).state;
assert.equal(state.field(field),beforeSelection,"caret moves must not scan or parse the document");
const region = state.field(field)[0]!;
state = state.update({changes:{from:region.from+7,to:region.from+11,insert:"revenue"}}).state;
assert.equal(state.field(field)[0]!.state.doc.toString(),"SELECT revenue FROM sales");
assert.match(syntaxTree(state.field(field)[0]!.state).toString(),/Statement/);
console.log("Composer lifecycle: reproduced override conflict; remount/HMR recovery preserves references and undo; SQL parse states reused.");
